### PR TITLE
Use platform specific fonts if Extrema fonts are not available

### PR DESCRIPTION
**Pull request by vadz**
I believe this should do the best possible thing, please check the last commit for the logic of the changes (the previous 2 just contain some minor cleanup).

### CODE REVIEW

**Comment by esternin** [comment]
Vadim, I am confused, you are removing toUpper, but the `if( )` only checks against a "SANS" etc, i.e. the user now *must* enter font name in UPPERCASE only?

I see how you made the wxFont look-up case-insensitive, but this is about syntax of the extrema command, `set font SANS` and `set font sans` should both yield the same result (FreeSans, hopefully, or something off the swiss list).

Where should we put a warning that "Warning: FreeFont family not installed, some special characters may not render properly" ?

**Comment by vadz** [comment]
As c7242c56cce858d77f6148419cc67588729777ca explains, this ctor is only used with 3 hard-coded upper-case names. There is another `Upper()` in `GRA_fontControl::GetFontCode()` which is applied to the input coming from user.

You can add the warning right before the code determining `wxFontFamily`, this function will only be called once for each facename. But I'd strongly recommend _not_ to show (3) message box(es) here or even one (if you use `wxLogWarning()`) as this will be supremely annoying for the people who can't or don't want to install these fonts for whichever reason. It would be better to show this warning in some less obtrusive way, e.g. in the main window somewhere (status bar?), but this would require slightly more work, e.g. setting some flag here if the facename is not available and checking for it later.

**Comment by esternin** [comment]
Also, while appropriate now, I think we should keep things you are removing in https://github.com/esternin/eXtrema/pull/49/commits/4721a338e85cd731bbe0429fb198c65a8c11ff4a, commented out, as in the future I would want to add an interactive dialog with a fontpicker here. 

I am thinking of adding an additional parameter to `set font` to provide the remapping:
```
set font sans FreeSans
```
would be the default, and any valid font name installed on the system would do here. A fontpicker dialog would provide a front end for this command.

If I remove my own PostScript generation, as you suggested, and stick with cairo-based SVG hardcopy generation, this will probably conform to what you think is the right way to handle fonts.  This is an enhancement for the future, though.  If you agree, we should open it up as an issue for future work, but at least the comments in the above merge should be kept?

**Comment by esternin** [comment]
> It would be better to show this warning in some less obtrusive way, e.g. in the main window somewhere 

Sure, we have the text output area in Analysis Window,  this is where it should go.

As long as I generate EPS using FreeFont family only, must warn the users.  In fact, even screen renderings of certain characters may be affected, since different fonts floating about do not always implement a complete UTF8 character set, and even if they do, the characters are in different places.  Fonts in general are a mess, as you well know.

**Comment by vadz** [comment]
I honestly don't see anything valuable in the lines being removed and the comments seemed to be completely detached from anything done in the code (i.e. it did not use font families, not the font picker), so it looked like just a leftover to me.

If you'd like to provide user-defined remappings, this should probably go into `GRA_fontControl`, and we would indeed to restore the ctor from `wxFont` then, but I think it would be better to add the ctor when it's needed rather than keep the ctor which is not.

**Comment by esternin** [comment]
> As [c7242c5](https://github.com/esternin/eXtrema/commit/c7242c56cce858d77f6148419cc67588729777ca) explains, this ctor is only used with 3 hard-coded upper-case names. There is another `Upper()` in `GRA_fontControl::GetFontCode()` which is applied to the input coming from user.

Ah, OK, got it.  I thought I had seen two toUppers() somewhere, and only one here, this explains it.

**Comment by vadz** [comment]
> > It would be better to show this warning in some less obtrusive way, e.g. in the main window somewhere
> 
> Sure, we have the text output area in Analysis Window, this is where it should go.

Looks good.
 
> As long as I generate EPS using FreeFont family only, must warn the users.

Just to be clear, this change doesn't affect EPS generation at all. I don't know when would a warning about EPS make place to be honest, what really matters is whether FreeXXX fonts are available when _viewing_ them, not generating them, and you can't check for this.

**Comment by esternin** [comment]
> I think it would be better to add the ctor when it's needed rather than keep the ctor which is not.

I tend to keep bits that might come in handy, especially for things I have little experience with, but I guess this merge is saved in the github, so one should be able to find it later.

**Comment by esternin** [comment]
I see also that your first preference is the exact match, so `set font arial` is going to work when Arial is available, even if FreeFonts are installed, and generate no warnings.

So what will happen at the time of EPS generation?

**Comment by esternin** [comment]
> Just to be clear, this change doesn't affect EPS generation at all.

??  I do not follow.  Only three Free* fonts are used and mapped into 256-character pages as required by the (UTF-unfriendly) PostScript in `GRA_postscript.cpp`, so after this change we will have a mismatch between screen and EPS, it seems to me.

**Comment by esternin** [comment]
> I see also that your first preference is the exact match

Actually, if someone installs a font named "sans" or "Sans" it will be the one used ahead of FreeSans, in this logic.

**Comment by vadz** [comment]
I'm afraid you still misunderstand how does the existing code work. Please look at `GetPostScriptFontName()` in `src/Graphics/GRA_fontControl.cpp`, it **always** returns FreeXXX font since your changes of df49116a, completely independently of the font actually used on screen. And because this is the function used in `src/Graphics/GRA_postscript.cpp`, your PS files are always generated with FreeXXX fonts, completely independently of the fonts actually available on the system -- and this PR doesn't change that.

As for choosing Sans if it's available, I thought this was what you wanted, i.e. FreeSans should be used only as fallback. If you prefer to use only FreeXXX, then it's even simpler as you can directly fall back on family-based font choice if they're not available. But this means you would start requiring having them under Linux too and I don't think you want that.

In any case, please feel free to change this code as you see fit, it shows how can you check for the font availability, so you can implement whichever logic you want in a similar way.

**Comment by esternin** [comment]
Leaving the PS generation aside for the moment....

> As for choosing Sans if it's available, I thought this was what you wanted, i.e. FreeSans should be used only as fallback. If you prefer to use only FreeXXX, then it's even simpler as you can directly fall back on family-based font choice if they're not available. But this means you would start requiring having them under Linux too and I don't think you want that.

Like I had said, perhaps not so clearly, my preference has been to treat "sans", "serif", and "mono" as extrema's internal names for the fonts.  These names would NOT be the actual font names; instead, they would be mapped onto the actual font names / .ttf font files, preferably from the FreeFont family but failing that, to something similar.  If there was a way to identify all Type 42 .ttf files on the system, those files would be the most appropriate to select from for both screen and PostScript generation, and would ensure consistency between screen and hardcopy.  

I have been requiring (in the INSTALL file) freefonts to be installed under Linux since we begun this project, it's a trivial addition on every known distribution.  I definitely want that! - and it requires no effort at all under Linux, except for one `apt-get install...` command.

> In any case, please feel free to change this code as you see fit, it shows how can you check for t

I will merge the changes, and thanks for showing me how to make them, but I will have to think about the logic of font selection some more.  I do not fully agree with your preferred sequence of choices, so I probably need to do some testing to decide how bad the results are, and maybe change the sequence a bit.  The exact placement of every character on the page, and the exact match across platforms and from screen to hardcopy are important, and you feel a lot more relaxed about that than I do.  One of my major beefs with gnuplot and matlab is their very casual treatment of screen/postscript "matching", which simply does not deserve the term, and I definitely do not want to go that route.

> ... you still misunderstand how does the existing code work. Please look at GetPostScriptFontName() in src/Graphics/GRA_fontControl.cpp, it always returns FreeXXX font since your changes of df49116, completely independently of the font actually used on screen. 

I am sure you are right about me!  but the problem has been the screen fonts *not* being FreeFonts, not the PostScript fonts *being* FreeFonts.  But with your current changes, especially changes in the logic, those now need to be re-done to match whatever your new selector chooses, however poor the results. 

Or maybe it's not needed at all? If the default is to use the same .ttf file, mapping font "FreeSans" onto "FreeSans.ttf" should be unnecessary.  I always thought that BOTH screen and PostScript fonts had to be selected, so the code in `GRA_fontControl.cpp` - to me - simply builds a dictionary of FontName -> PSFontName, to be used in `GRA_postscript.cpp` for EPS generation..  (Actually, I had thought of it as ExtremaFontName -> PSFontName, with ExtremaFontName -> ScreenFontName being a separate dictionary, but you are switching to the actual font names as ExtremaFontNames, so that dictionary is gone. Perhaps the PS disctionary is no longer needed as well?)

If the selection is FreeFont, and it is found then *I know* the same .ttf file will work for both, and I am completely unsure of that for almost any other font.  Arial under Win XP and Arial in HP PostScript and the one claiming to be UTF8 compliant in Win10 and ten other fonts self-identifying as Arial-like all have mismatched encoding schemes, and could never be made to match, not predictably, anyway.  Restricting to FreeFonts seemed to me like a good way to restore some predictability in that process.

**Comment by vadz** [comment]
Sorry for misunderstanding you about "Sans" etc, I did think you wanted to use those under Linux (because they correspond to the standard fonts names there and if you don't want to use them, finally, then I don't understand at all why did you switch to them from the previously used fonts in 829196be05bfa3f201bcc8b4d5e9ce84774095c1). If you don't, then we shouldn't try them at all. The only thing I'd like to say is that if you want to use `psFontNames_` for something other than PS fonts (e.g. screen fonts), then you really ought to rename it because it's incredibly confusing otherwise.

But concerning EPS, I only mentioned it because you seemed to link them with the changes here, but they don't affect them at all.

**Comment by esternin** [comment]
"SANS" in Linux, historically, has been a way to declare "a sans fonts from whatever family", and it changes from distro to distro, from version to version.  Sometimes it translates into DejaVu Sans, sometimes into Liberation Sans, etc.  In eXtrema I wanted to maintain this non-foundry-specific way of asking for a *type* of font. So yes, looking for a specific font aliased to "SANS" maybe should not be done at all.  Certainly I propose
```
@@ -30,19 +30,19 @@ wxFontInfo GetAvailableVariantOf(wxString const& name)
 
   wxFontInfo info(12);
 
+  // Prefer one of the FreeFonts that we install with Extrema 
+  wxString nameBest = "Free" + name;
+  if ( allFacenames.Index(nameBest, false /* case-insensitive */) != wxNOT_FOUND )
+    return info.FaceName(nameBest);
+
+  // Find an available alternative. Is there an actual font "SANS", "SERIF", or "MONO"?
   if ( allFacenames.Index(name, false /* case-insensitive */) != wxNOT_FOUND )
   {
     // This font is available, just use it directly.
     return info.FaceName(name);
   }
 
-  // Find an available alternative: start by the fonts that we install with
-  // Extrema that should be always available.
-  wxString nameAlt = "Free" + name;
-  if ( allFacenames.Index(nameAlt, false /* case-insensitive */) != wxNOT_FOUND )
-    return info.FaceName(nameAlt);
-
-  // If they aren't, just fall back to the corresponding default font of the
+  // Fall back to the corresponding default font of the
   // given family for the current platform.
   wxFontFamily family;
   if ( name == "SANS" )
```

I switched to the FreeFont family from some Windowesque font selection because in the past it relied on actually distributing old non-UTF8 fonts with the program.  In the meantime, Windows replaced those fonts with newer version, and Linux picked up compatible versions from other foundries, but with a different character mappings, so I felt it was a mess.  On the other hand, the list did not get built based on what already was available on the system. 

P.S. Somehow, again, I did some stupid merge that repeated what your pr already did, I do not understand how.  Could you kill it, as it seems superfluous.  I did `git reset --hard HEAD~1`, but this is at my end and I can't find the corresponding button on github to erase it...  Could you clean this up?

**Comment by esternin** [comment]
> The only thing I'd like to say is that if you want to use psFontNames_ for something other than PS fonts (e.g. screen fonts), then you really ought to rename it because it's incredibly confusing otherwise.

Wait, but that's precisely what I have been arguing: PS fonts and screens fonts should be the same, from the same .ttf file.  Do I *need* to declare that in `GRA_fontControl.cpp` at all?  With your changes, I feel `Initialize()` should only declare the internal default settings - they will not get used until the first wxFont creation, and populating `psFontNames_.insert(...);` should be done in-sync with whatever your new selector does, in `GRA_font.cpp`.  If at all...

**Comment by vadz** [comment]
Sorry, I have to log off for today, so just one last comment for today:

1. You have done another merge in the wrong direction, possibly because you did `git pull` after merging locally. Please make sure to set your `pull.ff` git option to "only", as previously recommended, to make sure this doesn't happen accidentally. However there is nothing to undo/clean up here, the history is a bit ugly, but the contents is fine.
2. Screen and PS fonts are handled completely differently in the current code. I have no idea why was it done (and continued to be done by you in your several commits changing this code) if you always want them to be the same. I also completely disagree that they should be the same, of course, because as mentioned many times before the fonts available on the machine generating the EPS file have absolutely nothing to do with the fonts available on the machine where it's viewed, so there is no possible reason to change the fonts in EPS based on the presence or absence of any fonts on the machine generating it. But if this is what you want to do, you can do it and the code will be even simpler.
3. Your patch above is fine if you don't want to use "Sans" etc under Linux but I would then go further and remove the code trying to use "Sans" completely (rather than still trying to do it after trying "FreeSans"). This, of course, boils down to what I had proposed from the very beginning: use your fonts if they're available and standard font of the same family otherwise and this makes perfect sense to me.

**Comment by esternin** [comment]
OK, thanks and g'night.
1. ok, thanks.
3. I have never resisted that, except for the need to map onto the same PS fonts.
2. The very same FreeFont files, installed under Linux and Windows render three characters incorrectly on the screen under Windows. The eps rendered under windows shows all correct symbols under Linux. So the new code does not select FreeSans as the screen font under Windows, or yet again, the my understanding that FreeSans.ttf file contains BOTH the screen and PS fonts within it are incorrect.

**Comment by esternin** [comment]
Let's just agree to disagree on the non-portability of fonts. Until I add the code to actually include the fonts in the eps file itself we'll never agree.  But here I have two systems that BOTH have the SAME .ttf files installed, and yet...

**Pull request merged**
