### PR TITLE
Fixes for MSW build

### PR DESCRIPTION
**Pull request by vadz**
These changes are enough to get a minimally working Windows version, i.e. you can run it and do things with it. There are many problems in it, however, here are some that I already noticed (but there are probably many more):

1. Running scripts from the "Execute" dialog doesn't work due to wrong paths parsing somewhere, colons in MSW file names seem to be misinterpreted/not recognized (running scripts using just their relative file name, without colon, using `@` from the main window does work).
2. Icons in the toolbars and bitmap buttons look weirdly ugly due to some kind of a border around them, e.g. look at this toolbar. This is probably simple to fix by using `wxNO_BORDER` style for the buttons. On an unrelated note, I hadn't even realized that Extrema didn't use `wxToolBar` for this, it probably should (i.e. it would look better).
3. Many windows look ugly because they have dark grey background, corresponding to the default `wxFrame` background, with lighter grey for the parts covered by `wxPanel`s. This is also not difficult to fix, and would have other advantages (e.g. keyboard navigation using TAB would work if there is a parent `wxPanel` covering the entire frame), but there are quite a few such windows.

I'll probably try fixing those in the order listed, unless you prefer to do it yourself and ask me to do something more difficult (please let me know).

See #12.

### CODE REVIEW

**Comment by esternin** [comment]
> we can switch to 3.1.6.
Actually, no we can't - it's not released yet!

Before we merge, I want to re-build with whatever version is best suited for this branch (MSW) . Is it the latest released version, 3.0.5, or 3.1.5 which I thought was necessary for MSW, but had bugs that would be fixed in 3.1.6 ?

**Comment by esternin** [comment]
Alas, under 3.0.5: the icon setting did not work; the size of Help and Quit buttons is weirdly out of line with the others; a canvas resize refreshes the graphics part, though not resizes it, and  the background part of the canvas is messed up (backing storage?); and the path processing is still messed up.
image

**Comment by vadz** [comment]
I've fixed the visualization window refresh and status bar (dis)appearance (which were related).

I've also fixed an assert that could happen when resizing the window to be too small.

I'll look at the path issues next, but not today.

**Comment by vadz** [comment]
I think this should be merged now.

**Pull request merged**
